name: Run mkepg.sh with jq

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */8 * * *'  # Запуск каждые 8 часов

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run mkepg.sh
        run: |
          bash mkepg.sh > epgm.xml

      - name: Archive epgm.xml
        run: gzip -f epgm.xml
          
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email your-email@example.com
          git add epgm.xml.gz
          git commit -m "Convert JSON to XMLTV and archive"
          git push
